# Generated by Django 6.0.3 on 2026-04-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_service_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
