# Generated by Django 6.0.3 on 2026-04-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_service_app', '0002_material_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
