# Generated by Django 6.0.3 on 2026-04-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_service_app', '0004_courseqa_studentnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='start_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
