# Generated by Django 6.0.3 on 2026-04-15 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_seed_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userroles',
            name='assigned_at',
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roles'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.AlterModelTable(
            name='userroles',
            table=None,
        ),
    ]
